cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from shop.views import RegisterFormView

urlpatterns = [
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('authorization/', include(('authorization.urls', 'authorization'), namespace='authorization')),
    path('', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/shop/', permanent=True)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from django.conf.urls import url
from shop import views
from .views_example import ProductCreate, ProductUpdate, ProductDelete

urlpatterns = [
    url(r'^register/$', views.RegisterFormView.as_view()),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

urlpatterns += [
    url(r'^product/create/$', ProductCreate.as_view(), name='product_create'),
    url(r'^product/(?P<pk>\d+)/update/$', ProductUpdate.as_view(), name='product_update'),
    url(r'^product/(?P<pk>\d+)/delete/$', ProductDelete.as_view(), name='product_delete'),
]

cart/forms.py
from django import forms

PRODUCT_CHOICES_COUNT = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    count = forms.TypedChoiceField(choices=PRODUCT_CHOICES_COUNT, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.views.decorators.http import require_POST
from cart.cart import Cart
from django.shortcuts import get_object_or_404, render, redirect
from shop.models import Product
from .forms import CartAddProductForm
from django.conf import settings


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        c_data = form.cleaned_data
        cart.add(product=product,
                 count=c_data['count'],
                 update_count=c_data['update'])

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', context={settings.SESSION_ID_CART: cart})

cart/templates/cart/detail.html
{% extends "base.html" %}

{% load static %}
{% block title %}
    Shopping cart
{% endblock %}

{% block content %}
    <h2>Shopping </h2>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Count</th>
            <th>Remove</th>
            <th>Price</th>
            <th>Total price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                    {% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.count }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Continue shopping</a>
        <a href="{% url "orders:order_create" %}" class="button">Checkout</a>
    </p>
{% endblock %}