cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from shop.views import RegisterFormView

urlpatterns = [
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('authorization/', include(('authorization.urls', 'authorization'), namespace='authorization')),
    path('', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/shop/', permanent=True)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.conf.urls import url
from shop import views
from .views_example import ProductCreate, ProductUpdate, ProductDelete

urlpatterns = [
    url(r'^register/$', views.RegisterFormView.as_view()),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

urlpatterns += [
    url(r'^product/create/$', ProductCreate.as_view(), name='product_create'),
    url(r'^product/(?P<pk>\d+)/update/$', ProductUpdate.as_view(), name='product_update'),
    url(r'^product/(?P<pk>\d+)/delete/$', ProductDelete.as_view(), name='product_delete'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name="product",
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    thumbnail = models.ImageField(upload_to="products/%Y/%m/%d", blank=True, null=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    available = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    def __str__(self):
        return self.name


class Comment(models.Model):
    product = models.ForeignKey(Product, related_name="comments", on_delete=models.CASCADE,)
    name = models.CharField(max_length=200)
    approved = models.BooleanField(default=True)
    email = models.EmailField()
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('update_date',)

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

shop/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Comment

class MyUserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        def save(self, commit=True):
            user = super(MyUserCreateForm, self).save(commit=False)
            user.email = self.cleaned_data['email']
            if commit:
                user.save()
            return user


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'text', 'email',)

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Comment
from cart.forms import CartAddProductForm
from django.views.generic.edit import FormView
from .forms import MyUserCreateForm, CommentForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {'category': category,
               'categories': categories,
               'products': products}

    return render(request, 'shop/product/list.html', context=context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    comments = product.comments.filter(approved=True)

    cart_form = CartAddProductForm()
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.product = product
            new_comment.save()
            #flag = True
    comment_form = CommentForm()
    context = {'product': product,
               'cart_product_form': cart_form,
               'comment_form': comment_form,
               'comments': comments,
               #'comment_added': flag,
               }
    return render(request, 'shop/product/detail.html', context=context)


class RegisterFormView(FormView):
    form_class = MyUserCreateForm
    success_url = 'login/'
    template_name = 'shop/register.html'

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


    def form_invalid(self, form):
        return super(RegisterFormView, self).form_invalid(form)

shop/templates/shop/product/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
        <p class="price">${{ product.price }}</p>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
    </div>
    <div>
        {% with comments.count as c %}
            <h2>
                {{ c }}comments
            </h2>
        {% endwith %}
    </div>
    <div>
        {% for comment in comments %}
            <div class="comment">
                <p> comment by {{ comment.name }} </p>
                {{ comment.text }}
            </div>
            {% empty %}
            <p> there are no comments </p>

        {% endfor %}
    </div>
    <h2> Add comment </h2>
    <div>
        {% if comment_added %}
            <p> Your comment added </p>
        {% else %}
            <form method="post">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <p><input type="submit" value="Add comment"></p>
            </form>
        {% endif %}
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Categories{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <div>
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </div>

                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}